/**
 * Offline decomposition and sensitivity analysis of the risk score
 * (Eq. 1 in paper/paper.tex). Reads frozen evaluation results; makes NO API
 * calls and mutates nothing, so it is safe to run against a live experiment.
 *
 * WHY INVERSION IS NEEDED
 * The harness records each incident's final riskScore/riskTier but not the
 * inputs that produced them (the plan's self-reported riskLevel, rollback
 * presence, severity). Rather than guess, this script enumerates the entire
 * input space, computes the score each input vector would produce, and keeps
 * only those consistent with what was actually recorded. If the enumeration
 * cannot reproduce a recorded score, that is reported as a failure rather
 * than smoothed over — an unreproducible score would mean the formula in the
 * paper is not the formula in the code.
 *
 *   npx tsx scripts/risk-decomposition.ts scripts/eval-heldout-full-gptoss120b.json ...
 */

import fs from "fs";
import { loadResults } from "../src/evaluation/load-results";

// ── Eq. 1, transcribed from src/services/risk.service.ts ──
interface Inputs {
    riskLevel: "low" | "medium" | "high" | "critical";
    severityCritical: boolean;
    rollback: boolean;
    source: "template" | "memory" | "llm" | "fallback" | "unavailable";
    memHit: boolean;
    trust: boolean;
}

/** decision.engine.ts derives BOTH b and c from the planner's own riskLevel. */
function blastRadius(riskLevel: Inputs["riskLevel"]): number {
    return riskLevel === "critical" ? 5 : riskLevel === "high" ? 3 : 2;
}
function confidence(riskLevel: Inputs["riskLevel"]): number {
    return riskLevel === "low" ? 0.9 : riskLevel === "medium" ? 0.7 : 0.5;
}

interface Terms {
    blast: number;
    confidence: number;
    severity: number;
    rollback: number;
    template: number;
    trust: number;
    memHit: number;
}

function terms(i: Inputs): Terms {
    return {
        blast: blastRadius(i.riskLevel) * 20,
        confidence: Math.round((1 - confidence(i.riskLevel)) * 30),
        severity: i.severityCritical ? 15 : 0,
        rollback: i.rollback ? -20 : 0,
        template: i.source === "template" ? -25 : 0,
        trust: i.trust ? -15 : 0,
        memHit: i.memHit && !i.trust ? -5 : 0,
    };
}

const unclamped = (t: Terms) => Object.values(t).reduce((a, b) => a + b, 0);
const clamp = (n: number) => Math.max(0, Math.min(100, n));

function tierOf(score: number): string {
    if (score < 35) return "auto";
    if (score < 65) return "notify";
    if (score < 85) return "approve";
    return "block";
}

/** Every input vector the pipeline can actually produce. */
function enumerateInputs(): Inputs[] {
    const out: Inputs[] = [];
    for (const riskLevel of ["low", "medium", "high", "critical"] as const)
        for (const severityCritical of [true, false])
            for (const rollback of [true, false])
                for (const source of ["template", "memory", "llm", "fallback", "unavailable"] as const)
                    for (const memHit of [true, false])
                        for (const trust of [true, false]) {
                            // trust/memHit only meaningful for memory-sourced plans
                            if ((memHit || trust) && source !== "memory") continue;
                            if (trust && !memHit) continue;
                            out.push({ riskLevel, severityCritical, rollback, source, memHit, trust });
                        }
    return out;
}

const SPACE = enumerateInputs();

interface Row {
    scenario: string;
    planSource: string;
    riskScore: number;
    riskTier: string;
}

/** Display labels for the paper's risk-ablation figure (Fig. 2). */
const FIGURE_LABELS: Record<keyof Terms, string> = {
    blast: "Blast radius",
    severity: "Severity",
    confidence: "Confidence",
    rollback: "Rollback",
    template: "Template source",
    trust: "Trusted memory",
    memHit: "Memory hit",
};

/**
 * Writes the full arm's one-at-a-time sensitivity counts as a TeX data file
 * that paper/figures/risk_ablation.tex draws from, so the figure's bars come
 * from this analysis rather than from separately typed numbers.
 */
function writeAblationTex(path: string, source: string, n: number, counts: Record<keyof Terms, number>): void {
    const order: (keyof Terms)[] = ["blast", "severity", "confidence", "rollback", "template", "trust", "memHit"];
    const rows = order.map((k) => `${FIGURE_LABELS[k]}/${counts[k]}`).join(",\n  ");
    fs.writeFileSync(
        path,
        `% AUTO-GENERATED by autoops_ai/scripts/risk-decomposition.ts -- do not edit.\n` +
        `% Source: ${source.split("/").pop()} (one-at-a-time term ablation of Eq. 1)\n` +
        `\\def\\ablationN{${n}}\n` +
        `\\def\\ablationRows{\n  ${rows}}\n`
    );
    console.log(`\n    wrote figure data → ${path}`);
}

function main() {
    const args = process.argv.slice(2);
    const ablationTex = args.find((a) => a.startsWith("--ablation-tex="))?.split("=")[1];
    const files = args.filter((a) => !a.startsWith("--"));
    if (!files.length) {
        console.error("usage: risk-decomposition.ts <results.json> [...] [--ablation-tex=<out.tex>]");
        process.exit(1);
    }

    for (const file of files) {
        const d = loadResults(file);
        const rows: Row[] = d.results
            .filter((r: any) => r.riskScore !== null)
            .map((r: any) => ({
                scenario: r.scenario,
                planSource: r.planSource,
                riskScore: r.riskScore,
                riskTier: r.riskTier,
            }));

        console.log(`\n${"=".repeat(72)}\n${file}  (arm=${d.meta.arm}, n=${rows.length} scored)\n${"=".repeat(72)}`);

        // ── 1. Reproduce every recorded score from the formula ──
        let reproduced = 0;
        const consistentFor = new Map<string, Inputs[]>();
        for (const row of rows) {
            const key = `${row.planSource}|${row.riskScore}`;
            if (!consistentFor.has(key)) {
                const matches = SPACE.filter(
                    (i) => i.source === row.planSource && clamp(unclamped(terms(i))) === row.riskScore
                );
                consistentFor.set(key, matches);
            }
            if (consistentFor.get(key)!.length > 0) reproduced++;
        }
        console.log(`\n[1] Formula reproduces recorded score: ${reproduced}/${rows.length}` +
            (reproduced === rows.length ? "  ✓ (paper's Eq. 1 == shipped code)" : "  ✗ MISMATCH — investigate"));

        // ── 2. Observed score distribution and saturation ──
        const dist = new Map<number, number>();
        for (const r of rows) dist.set(r.riskScore, (dist.get(r.riskScore) || 0) + 1);
        const sorted = [...dist.entries()].sort((a, b) => a[0] - b[0]);
        console.log(`\n[2] Observed scores: ${sorted.map(([s, n]) => `${s}(n=${n})`).join("  ")}`);
        console.log(`    Distinct values: ${sorted.length} across ${rows.length} incidents`);
        const atCeiling = dist.get(100) || 0;
        console.log(`    At ceiling (100): ${atCeiling}/${rows.length} = ${(100 * atCeiling / rows.length).toFixed(1)}%`);

        // ── 3. Term decomposition per observed score ──
        console.log(`\n[3] Term decomposition (per distinct observed score):`);
        for (const [score, n] of sorted) {
            const key = [...consistentFor.keys()].find((k) => k.endsWith(`|${score}`));
            const cands = key ? consistentFor.get(key)! : [];
            if (!cands.length) { console.log(`    score ${score}: no consistent input vector`); continue; }
            // Report the decomposition; note ambiguity rather than hiding it.
            const t = terms(cands[0]);
            const raw = unclamped(t);
            const levels = [...new Set(cands.map((c) => c.riskLevel))];
            console.log(
                `    score ${String(score).padStart(3)} (n=${String(n).padStart(3)}): ` +
                `blast +${t.blast}, conf +${t.confidence}, sev +${t.severity}, ` +
                `rollback ${t.rollback}, tmpl ${t.template}, trust ${t.trust}, mem ${t.memHit}` +
                `  → raw ${raw} → clamped ${clamp(raw)}` +
                (raw > 100 ? `  [SATURATED: ${raw - 100} pts discarded]` : "") +
                (levels.length > 1 ? `  (riskLevel ambiguous: ${levels.join("/")})` : `  (riskLevel=${levels[0]})`)
            );
        }

        // ── 4. Sensitivity: zero each term, count tier changes ──
        console.log(`\n[4] Sensitivity — zero one term, how many incidents change tier:`);
        const termNames: (keyof Terms)[] = ["blast", "confidence", "severity", "rollback", "template", "trust", "memHit"];
        const changedBy = {} as Record<keyof Terms, number>;
        for (const name of termNames) {
            let changed = 0;
            let inert = 0;
            for (const row of rows) {
                const key = `${row.planSource}|${row.riskScore}`;
                const cands = consistentFor.get(key)!;
                if (!cands.length) continue;
                const t = terms(cands[0]);
                const baseTier = tierOf(clamp(unclamped(t)));
                const without = { ...t, [name]: 0 };
                const newTier = tierOf(clamp(unclamped(without)));
                if (newTier !== baseTier) changed++;
                // A term is inert when removing it changes nothing because the
                // score was saturated above the ceiling anyway.
                else if (unclamped(t) > 100 && unclamped(without) >= 100 && t[name] !== 0) inert++;
            }
            console.log(`    ${name.padEnd(11)} → tier changes: ${String(changed).padStart(3)}/${rows.length}` +
                (inert ? `   (inert on ${inert} saturated incidents)` : ""));
            changedBy[name] = changed;
        }
        if (ablationTex && d.meta.arm === "full") writeAblationTex(ablationTex, file, rows.length, changedBy);

        // ── 5. Routing distribution ──
        const tiers = new Map<string, number>();
        for (const r of rows) tiers.set(r.riskTier, (tiers.get(r.riskTier) || 0) + 1);
        console.log(`\n[5] Routing distribution:`);
        for (const t of ["auto", "notify", "approve", "block"]) {
            const n = tiers.get(t) || 0;
            console.log(`    ${t.padEnd(8)} ${String(n).padStart(3)}  (${(100 * n / rows.length).toFixed(1)}%)`);
        }
        const gated = (tiers.get("approve") || 0) + (tiers.get("block") || 0);
        console.log(`    → human-gated: ${gated}/${rows.length} (${(100 * gated / rows.length).toFixed(1)}%)`);
        console.log(`    → ungated autonomous (auto): ${tiers.get("auto") || 0}`);
    }
}

main();
